# Generated by Django 4.0.4 on 2022-05-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=25)),
                ('d_o_b', models.DateField()),
                ('favourite_food', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'favourite_food',
            },
        ),
    ]
