# Generated by Django 4.0.4 on 2022-05-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0002_employee_alter_userassetdetail_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
